import { FC } from 'react';
import Head from 'next/head';
import { ContactProps } from '.';
import { NewFooterFeedback } from '@/components/ui/NewFooterFeedback';

export const Contact: FC<ContactProps> = (props) => {
  return (
    <>
      <Head>
        <title>О нас</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div {...props}></div>
      <NewFooterFeedback />
    </>
  );
};
